modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/superworldsun/SupersLegend/issues"
license="GPL-3"
[[mods]]
modId = "superslegend"
version = "0.0.1"
displayName = "SupersLegend"
logoFile="icon.png"
displayURL = "https://discord.gg/nSAvsr5"
authors = "superworldsun"
credits = "All contributors and testers"
description = '''This is a Zelda mod created by superworldsun'''

[[dependencies.superslegend]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.20.1-5.2.0,)"
    ordering = "AFTER"
    side = "BOTH"