modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/superworldsun/SupersLegend/issues"
license="${mod_license}"
[[mods]]
# While this shows an error, it does work fine, do not change it.
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile="icon.png"
displayURL = "https://discord.gg/nSAvsr5"
authors = "${mod_authors}"
credits = "All contributors and testers"
description = "${mod_description}"

# While this shows an error, it does work fine, do not change it.
[[dependencies.${mod_id}]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.20.1-5.2.0,)"
    ordering = "AFTER"
    side = "BOTH"